// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzeuratnmzsrmeipkuoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6ZXVyYXRubXpzcm1laXBrdW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTIxMzMsImV4cCI6MjA2NjYyODEzM30.UCCmhQ1tZj97fhaZQ4SbpJ7mruqaVz1tV8qkAR7ztJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);